export const metadata = {
  title: 'Bright Future & IT Solutions',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="/favicon.ico" rel="icon" />
        <link rel="stylesheet" href='assets/css/style.css' />
        <link rel="stylesheet" href='assets/css/globals.css' />
        <link rel='stylesheet' href='assets/vendor/bootstrap-icons/bootstrap-icons.css' />
        <link rel='stylesheet' href='assets/vendor/glightbox/css/glightbox.min.css' />
        <link rel='stylesheet' href='assets/vendor/boxicons/css/boxicons.min.css' />
        <link rel='stylesheet' href='assets/vendor/remixicon/remixicon.css' />
        <link rel='stylesheet' href='assets/vendor/swiper/swiper-bundle.min.css' />
        <link rel='stylesheet' href='assets/vendor/bootstrap/css/boostrap.min.css' />
        <link href="https://fonts.googleapis.com/css2?family=Cormorant:ital,wght@0,300..700;1,300..700&display=swap" rel="stylesheet"></link>
        <script src='assets/vendor/glightbox/js/glightbox.min.js' />
        {/* <script src='assets/vendor/isotope-layout/isotope.pkgd.min.js' /> */}
        <script src='assets/vendor/swiper/swiper-bundle.min.js' />
        <script src='assets/vendor/waypoints/noframework.waypoints.js' />
        <script src='assets/vendor/bootstrap/js/bootstrap.bundle.min.js' />
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w==" crossorigin="anonymous" referrerpolicy="no-referrer" /> */}
        {/* <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js" integrity="sha512-A7AYk1fGKX6S2SsHywmPkrnzTZHrgiVT7GcQkLGDe2ev0aWb8zejytzS8wjo7PGEXKqJOrjQ4oORtnimIRZBtw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> */}
        <script type="javascript" src="assets/js/main.js" defer />
      </head>
      <body>{children}
      </body>
    </html>
  )
}
